/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void RootNote_click1(GDropList source, GEvent event) { //_CODE_:RootNote:534536:
  myScale.setRoot(source.getSelectedIndex());
  myScale.buildScale();
  myScale.show();
} //_CODE_:RootNote:534536:

public void Scale_click1(GDropList source, GEvent event) { //_CODE_:Scale:869260:
  myScale.setScale(source.getSelectedIndex());
  myScale.buildScale();
  myScale.show();
} //_CODE_:Scale:869260:

public void Mode_change1(GCustomSlider source, GEvent event) { //_CODE_:Mode:779935:
  myScale.setMode(source.getValueI() - 1);
  myScale.buildScale();
  myScale.show();
} //_CODE_:Mode:779935:

public void ScaleNo_change1(GTextField source, GEvent event) { //_CODE_:ScaleNo:633112:
  println("ScaleNo - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ScaleNo:633112:

public void preserve_clicked1(GCheckbox source, GEvent event) { //_CODE_:preserve:378756:
  myScale.setPreserve(source.isSelected());
  myScale.buildScale();
  myScale.show();
} //_CODE_:preserve:378756:

public void Octave_change1(GCustomSlider source, GEvent event) { //_CODE_:Octave:839974:
  myScale.setOctave(source.getValueI());
  myScale.show();
} //_CODE_:Octave:839974:

public void Play_click1(GButton source, GEvent event) { //_CODE_:Play:541965:
  playPos = -1;

  if (isPlaying)
  {
    isPlaying = false;
    ac.stop();
    source.setText("Play");
  }
  else
  {
    isPlaying = true;
    ac.start();
    source.setText("Stop");
  }
} //_CODE_:Play:541965:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("ScaleBuilder V0.1");
  RootNote = new GDropList(this, 80, 24, 112, 220, 10, 10);
  RootNote.setItems(loadStrings("list_534536"), 0);
  RootNote.addEventHandler(this, "RootNote_click1");
  Scale = new GDropList(this, 80, 96, 112, 220, 10, 10);
  Scale.setItems(loadStrings("list_869260"), 0);
  Scale.addEventHandler(this, "Scale_click1");
  Mode = new GCustomSlider(this, 80, 116, 112, 56, "blue18px");
  Mode.setShowValue(true);
  Mode.setLimits(1, 1, 12);
  Mode.setNbrTicks(12);
  Mode.setStickToTicks(true);
  Mode.setShowTicks(true);
  Mode.setEasing(2.0);
  Mode.setNumberFormat(G4P.INTEGER, 0);
  Mode.setOpaque(false);
  Mode.addEventHandler(this, "Mode_change1");
  label1 = new GLabel(this, 16, 24, 48, 20);
  label1.setText("Root:");
  label1.setOpaque(false);
  label2 = new GLabel(this, 16, 96, 48, 20);
  label2.setText("Scale:");
  label2.setOpaque(false);
  label3 = new GLabel(this, 16, 132, 48, 20);
  label3.setText("Mode:");
  label3.setOpaque(false);
  ScaleNo = new GTextField(this, 80, 196, 112, 16, G4P.SCROLLBARS_NONE);
  ScaleNo.setOpaque(true);
  ScaleNo.addEventHandler(this, "ScaleNo_change1");
  label4 = new GLabel(this, 16, 196, 48, 16);
  label4.setText("No:");
  label4.setOpaque(false);
  preserve = new GCheckbox(this, 16, 164, 80, 20);
  preserve.setIconPos(GAlign.EAST);
  preserve.setText("Preserve:");
  preserve.setOpaque(false);
  preserve.addEventHandler(this, "preserve_clicked1");
  Octave = new GCustomSlider(this, 80, 48, 112, 48, "blue18px");
  Octave.setShowValue(true);
  Octave.setLimits(1, 0, 5);
  Octave.setNbrTicks(6);
  Octave.setStickToTicks(true);
  Octave.setShowTicks(true);
  Octave.setEasing(2.0);
  Octave.setNumberFormat(G4P.INTEGER, 0);
  Octave.setOpaque(false);
  Octave.addEventHandler(this, "Octave_change1");
  label5 = new GLabel(this, 16, 64, 80, 20);
  label5.setText("Octave:");
  label5.setOpaque(false);
  Play = new GButton(this, 8, 236, 392, 20);
  Play.setText("Play");
  Play.addEventHandler(this, "Play_click1");
}

// Variable declarations 
// autogenerated do not edit
GDropList RootNote; 
GDropList Scale; 
GCustomSlider Mode; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GTextField ScaleNo; 
GLabel label4; 
GCheckbox preserve; 
GCustomSlider Octave; 
GLabel label5; 
GButton Play; 
